# Generated by Django 5.0.3 on 2024-03-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/message_files/img/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/message_files/file/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(related_name='message_history', to='chat_app.message')),
                ('pinned_messages', models.ManyToManyField(blank=True, related_name='pinned_messages', to='chat_app.message')),
            ],
        ),
        migrations.CreateModel(
            name='ChatP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_init', to=settings.AUTH_USER_MODEL)),
                ('message_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_history', to='chat_app.messagehitory')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_icon', models.ImageField(blank=True, null=True, upload_to='chat/group/icons/')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('message_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2g_history', to='chat_app.messagehitory')),
            ],
        ),
    ]
