# Generated by Django 5.0.3 on 2024-04-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, related_name='message_history', to='chat_app.message')),
                ('pinned_messages', models.ManyToManyField(blank=True, related_name='pinned_messages', to='chat_app.message')),
            ],
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='message_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2g_history', to='chat_app.messagehistory'),
        ),
        migrations.AlterField(
            model_name='chatp2p',
            name='message_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_history', to='chat_app.messagehistory'),
        ),
        migrations.DeleteModel(
            name='MessageHitory',
        ),
    ]
